<?php

########################################################################
# Extension Manager/Repository config file for ext: "categories_example"
#
# Auto generated by Extbase Kickstarter 2014-01-01
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Categories Example',
	'description' => 'Example of using sys_categories and extbase/fluid in FE',
	'category' => 'frontend',
	'author' => 'Torsten Schrade',
	'author_email' => 'Torsten.Schrade@adwmainz.de',
	'author_company' => 'Academy of Sciences and Literature, Mainz, Academy of Sciences and Literature, Mainz',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.1.0-6.1.99',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>